### ISSUE TITLE
What should be the threshold for flagging pending recharges?

### ISSUE THREAD

**Issue by mriduljo** [francineloza/HIM-HFC-Action-Items#3]
There are few pending recharges from the last week? Very few as a percent of total sent - we should try to send them again. 

Related question: what is the threshold for flagging pending recharges to you?

**Comment by francineloza** [comment]
Resolved by email- 

see response below:
Yes, you are right, they continue sending throughout the day, and when I resend them manually, I keep retrying until we get through them all. Basically, the system is set up as a “queue”, but we stop running things at a certain time, rather than when the queue is cleared- so sometimes we stop running on a given day, but the queue has not cleared. When we start running things again the next day, we start tackling the queue again and add the new records to the back of the queue. Does that make sense? So for the time-being, I wouldn’t worry about pending recharges, unless they are still pending at the end of the next day.
